version: "3"
services:
  airq:
    image: pidofme/airq:0.1.0
    restart: unless-stopped

  nginx:
    image: nginx:1.13.10-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:8080
    restart: unless-stopped